"""add_templates_and_job_columns

Revision ID: 7316290cb6fe
Revises:
Create Date: 2026-05-01 16:18:15.304948

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7316290cb6fe"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("image_prompt", sa.String(length=2000), nullable=False),
        sa.Column("video_prompt", sa.String(length=2000), nullable=False),
        sa.Column("default_provider", sa.String(length=50), nullable=False),
        sa.Column("default_aspect", sa.String(length=10), nullable=False),
        sa.Column("default_duration", sa.Integer(), nullable=False),
        sa.Column("default_camera_preset", sa.String(length=50), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("jobs", sa.Column("template_id", sa.Integer(), nullable=True))
    op.add_column(
        "jobs",
        sa.Column(
            "provider", sa.String(length=50), nullable=False, server_default="seedance"
        ),
    )
    op.add_column(
        "jobs",
        sa.Column(
            "aspect_ratio", sa.String(length=10), nullable=False, server_default="9:16"
        ),
    )
    op.add_column(
        "jobs",
        sa.Column(
            "duration_seconds", sa.Integer(), nullable=False, server_default="10"
        ),
    )
    op.add_column(
        "jobs", sa.Column("camera_preset", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "jobs",
        sa.Column(
            "image_source",
            sa.String(length=20),
            nullable=False,
            server_default="generated",
        ),
    )
    op.add_column(
        "jobs", sa.Column("video_cost_calc_basis", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "jobs", sa.Column("video_progress_stage", sa.String(length=50), nullable=True)
    )
    # SQLite doesn't support ALTER COLUMN / ADD CONSTRAINT directly — use batch mode.
    with op.batch_alter_table("jobs") as batch_op:
        batch_op.alter_column(
            "pattern", existing_type=sa.VARCHAR(length=4), nullable=True
        )
        batch_op.create_foreign_key(
            "fk_jobs_template_id_templates",
            "templates",
            ["template_id"],
            ["id"],
        )
    # ### end Alembic commands ###

    # 既存5パターンを templates テーブルにシード
    from datetime import datetime, timezone
    from sqlalchemy import table, column, String, Integer, Boolean, DateTime

    templates_table = table(
        "templates",
        column("name", String),
        column("category", String),
        column("image_prompt", String),
        column("video_prompt", String),
        column("default_provider", String),
        column("default_aspect", String),
        column("default_duration", Integer),
        column("default_camera_preset", String),
        column("is_archived", Boolean),
        column("created_at", DateTime),
        column("updated_at", DateTime),
    )

    _seed_now = datetime.now(timezone.utc)

    seed_data = [
        {
            "name": "ロマンティック系（A）",
            "category": "matching_ad",
            "image_prompt": "Portrait photo of a warm Japanese woman in her late 30s to early 40s, soft natural makeup, gentle smile, casual-elegant blouse in muted rose tones, sitting at a cozy cafe by a rain-streaked window, soft bokeh background, natural window light, upper body shot, realistic photography, no text, not a real person, fictional character",
            "video_prompt": "The woman gently wraps her hands around a coffee cup and looks out at the rain, soft smile, slow cinematic camera pull-back, warm cafe ambience, peaceful romantic atmosphere",
            "default_provider": "seedance",
            "default_aspect": "9:16",
            "default_duration": 10,
            "default_camera_preset": "dolly_out",
            "is_archived": False,
            "created_at": _seed_now,
            "updated_at": _seed_now,
        },
        {
            "name": "楽しさ系（B）",
            "category": "matching_ad",
            "image_prompt": "Portrait photo of a cheerful Japanese woman in her early 40s, natural makeup, bright genuine laugh, casual colorful outfit, sitting on a park bench surrounded by greenery and sunlight, upper body shot, realistic photography, no text, not a real person, fictional character",
            "video_prompt": "The woman laughs lightly and brushes hair from her face, light breeze moves through the trees behind her, joyful energy, slow-motion capture, warm golden hour lighting",
            "default_provider": "seedance",
            "default_aspect": "9:16",
            "default_duration": 10,
            "default_camera_preset": "static",
            "is_archived": False,
            "created_at": _seed_now,
            "updated_at": _seed_now,
        },
        {
            "name": "信頼感系（C）",
            "category": "matching_ad",
            "image_prompt": "Portrait photo of a composed Japanese woman in her mid 40s, minimal elegant makeup, calm confident expression, smart casual blazer in navy or grey, modern office environment background, upper body shot, realistic photography, no text, not a real person, fictional character",
            "video_prompt": "The woman looks up from her desk and gives a small warm smile, calm and composed movement, soft office lighting, steady camera, professional yet approachable atmosphere",
            "default_provider": "seedance",
            "default_aspect": "9:16",
            "default_duration": 10,
            "default_camera_preset": "static",
            "is_archived": False,
            "created_at": _seed_now,
            "updated_at": _seed_now,
        },
        {
            "name": "ユーモア系（D）",
            "category": "matching_ad",
            "image_prompt": "Portrait photo of a fun playful Japanese woman in her late 30s, light natural makeup, mischievous grin, casual trendy outfit, stylish modern cafe background with colorful decor, upper body shot, realistic photography, no text, not a real person, fictional character",
            "video_prompt": "The woman notices the camera, breaks into a wide grin and gives a small wave, spontaneous and lighthearted movement, bright cafe atmosphere, handheld-style camera feel",
            "default_provider": "seedance",
            "default_aspect": "9:16",
            "default_duration": 10,
            "default_camera_preset": "static",
            "is_archived": False,
            "created_at": _seed_now,
            "updated_at": _seed_now,
        },
        {
            "name": "真面目系（E）",
            "category": "matching_ad",
            "image_prompt": "Portrait photo of an intellectual Japanese woman in her early 50s, elegant minimal makeup, thoughtful expression, simple sophisticated blouse, library or bookshelf background, soft reading lamp light, upper body shot, realistic photography, no text, not a real person, fictional character",
            "video_prompt": "The woman closes a book gently and looks up with a quiet confident smile, deliberate graceful movement, warm library lighting, slow zoom-in, intelligent serene atmosphere",
            "default_provider": "seedance",
            "default_aspect": "9:16",
            "default_duration": 10,
            "default_camera_preset": "dolly_in",
            "is_archived": False,
            "created_at": _seed_now,
            "updated_at": _seed_now,
        },
    ]
    op.bulk_insert(templates_table, seed_data)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support DROP CONSTRAINT / ALTER COLUMN directly — use batch mode.
    with op.batch_alter_table("jobs") as batch_op:
        batch_op.drop_constraint("fk_jobs_template_id_templates", type_="foreignkey")
        batch_op.alter_column(
            "pattern", existing_type=sa.VARCHAR(length=4), nullable=False
        )
        batch_op.drop_column("video_progress_stage")
        batch_op.drop_column("video_cost_calc_basis")
        batch_op.drop_column("image_source")
        batch_op.drop_column("camera_preset")
        batch_op.drop_column("duration_seconds")
        batch_op.drop_column("aspect_ratio")
        batch_op.drop_column("provider")
        batch_op.drop_column("template_id")
    op.drop_table("templates")
    # ### end Alembic commands ###
