services:
  b-manager:
    build: .
    container_name: b-manager
    restart: unless-stopped
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./token.json:/app/token.json
